http:
  listener: 
    host: "localhost"
    port: "8084"
    path: "/api/*"
  requestor:
    host: "localhost"
    port: "8082"
    routesPath: "/fastGoCall/routes"
    schedulesPath: "/fastGoCall/schedules"
    
    

    