http:
  listener: 
    host: "0.0.0.0"
    port: "8084"
    path: "/api/*"
  requestor:
    host: "0.0.0.0"
    port: "8082"
    routesPath: "/fastGoCall/routes"
    schedulesPath: "/fastGoCall/schedules"
    
    