http:
  listener: 
    host: "localhost"
    port: "8082"
    path: "/fastGoCall/{serviceType}"
    
db:
  mysql:
    database: "mulesoft"
    host: "localhost"
    port: "3306"
    username: "root"
    password: "root"