#%RAML 1.0
title: RetrieveconsolidatedRoutesandSchedule TravelOnTip SAPI
description: This API will fetch Routes and Schedules from TravelOnTip System API

uses: 
  common: /libraries/common/commonBusiness-library.raml
  routes: /libraries/routes/routeBusiness-library.raml
  schedule: /libraries/schedules/scheduleBusiness-library.raml



/{transportType}:
  /{transportCompany}:
    /routes:
      get:
        is:
          - common.transactionId
        responses:
          200:
            body:
              application/json:
                type: routes.getRoutesResponse
                example: !include /libraries/routes/examples/getRoutes-200Response-example.json
          400:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/400Response-example.json
          404:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/404Response-example.json
          500:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/500Response-example.json
                
    /schedules:
      get:
        is:
          - common.transactionId
          - common.departureLocationCode
          - common.destinationLocationCode
        responses:
          200:
            body:
              application/json:
                type: schedule.getScheduleResponse
                example: !include /libraries/schedules/examples/getSchedules-200Response-example.json
          400:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/400Response-example.json
          404:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/404Response-example.json
          500:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/500Response-example.json
                    

          